spring:
  datasource:
    url: ${DATABASE_URL}?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          characterEncoding: UTF-8

  security:
    oauth2:
      client:
        registration:
          apple:
            client-id: ${APPLE_CLIENT_ID}
            client-secret: ${APPLE_CLIENT_SECRET}
            scope: openid
            redirect-uri: ${APPLE_CLIENT_ID}/login/oauth2/code/apple
            authorization-grant-type: authorization_code
        provider:
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize
            token-uri: https://appleid.apple.com/auth/token
            jwk-set-uri: https://appleid.apple.com/auth/keys
            user-name-attribute: sub

apple:
  oauth2:
    revoke-token-uri: https://appleid.apple.com/auth/revoke
  client-id: ${APPLE_CLIENT_ID}
  client-secret: ${APPLE_CLIENT_SECRET}

logging:
  file:
    name: /var/log/myapp/application.log # 로그 파일 저장 위치
  level:
    root: INFO # 전체 로그 레벨 설정 (INFO 이상만 출력)

server:
  port: 8080
  servlet:
    session:
      cookie:
        same-site: None
        secure: true
    timeout: 30m
