name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Build without tests
      run: ./gradlew clean assemble

    - name: Check JAR file existence
      run: ls -l build/libs

    - name: Deploy to Server
      if: success()
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      run: |
        # Debug environment variables
        echo "=== Debugging Environment Variables ==="
        echo "DATABASE_URL: $DATABASE_URL"
        echo "DATABASE_USERNAME: $DATABASE_USERNAME"
        echo "SSH_USER: $SSH_USER"
        echo "SSH_HOST: $SSH_HOST"
        echo "======================================="

        # Start ssh-agent and add the private key
        eval "$(ssh-agent -s)"
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > private_key.pem
        chmod 600 private_key.pem
        ssh-add private_key.pem
    
        # Disable strict host key checking and create remote directory
        ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "mkdir -p ~/musinsa_observer"
    
        # Copy built JAR file to the server
        scp -r build/libs/team4-0.0.1-SNAPSHOT.jar $SSH_USER@$SSH_HOST:~/musinsa_observer/build/libs/
    
        # Start the application on the server
        ssh $SSH_USER@$SSH_HOST << 'EOF'
          pkill -f 'java -jar' || true
          cd ~/musinsa_observer/build/libs
          nohup java -jar -Dspring.profiles.active=prod team4-0.0.1-SNAPSHOT.jar &
        EOF

    - name: Clean up
      if: success()
      run: rm -f private_key.pem
