name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Java 환경 설정
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # 3. Gradle 빌드
      - name: Build Application
        run: ./gradlew clean build -x test

      # 4. 환경 변수 디버깅 (선택 사항: 확인용)
      - name: Debug environment variables
        run: |
          echo "DATABASE_URL: $DATABASE_URL"
          echo "DATABASE_USERNAME: $DATABASE_USERNAME"
          echo "SSH_USER: $SSH_USER"
          echo "SSH_HOST: $SSH_HOST"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      # 5. 원격 서버로 배포
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # 기존 JAR 프로세스 종료
            pkill -f 'java.*team4-0.0.1-SNAPSHOT.jar' || true

            # 디렉토리 준비
            mkdir -p ~/musinsa_observer/build/libs

            # 기존 JAR 삭제
            rm -f ~/musinsa_observer/build/libs/team4-0.0.1-SNAPSHOT.jar

            # 새로운 JAR 업로드
            cat > ~/musinsa_observer/build/libs/team4-0.0.1-SNAPSHOT.jar << 'EOF'$(cat build/libs/team4-0.0.1-SNAPSHOT.jar | base64 -w0)EOF
            base64 -d ~/musinsa_observer/build/libs/team4-0.0.1-SNAPSHOT.jar > ~/musinsa_observer/build/libs/team4-0.0.1-SNAPSHOT.jar

            # JAR 실행
            nohup java -jar -Dspring.profiles.active=prod ~/musinsa_observer/build/libs/team4-0.0.1-SNAPSHOT.jar > ~/musinsa_observer/nohup.out 2>&1 &
